platform :ios do    
    desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
        match(app_identifier: ENV["MOGISAN_IOS_APP_IDENTIFIER"])
    end

    desc 'Fetch certificates. Build the iOS application.'
    lane :build do
        certificates
        gym(
            scheme: "angry_mogisan",
            workspace: "./ios/angry_mogisan.xcworkspace",
            export_method: "ad-hoc"
        )
    end

    desc 'Fetch certificates, build and upload to App Center.'
    lane :beta do
        build
        appcenter_upload(
            api_token: ENV["MOGISAN_IOS_APPCENTER_API_TOKEN"],
            owner_name: "adebens-googlemail.com",
            app_name: "angry_mogisan-iOS",
            ipa: ENV["MOGISAN_IOS_APPCENTER_DISTRIBUTE_IPA"]
        )
    end
end

platform :android do
    desc 'Build the Android application.'
    lane :build do
        gradle(task: 'clean', project_dir: 'android/')
        gradle(task: 'assemble', build_type: 'release', project_dir: 'android/')
    end

    desc 'Build and upload to App Center.'
    lane :beta do
        build
        appcenter_upload(
            api_token: ENV["MOGISAN_ANDROID_APPCENTER_API_TOKEN"],
            owner_name: "adebens-googlemail.com",
            app_name: "Angry-Mogisan-Android",
            apk: ENV["MOGISAN_ANDROID_APPCENTER_DISTRIBUTE_APK"]
        )
    end
end