version: "3"

networks:
    local:
        driver: bridge

volumes:
    eventstore-volume-data:
    eventstore-volume-logs:
    rabbitmq-volume-data:
    rabbitmq-volume-logs:

services:
    identity:
        image: debens/service-identity
        container_name: "identity"
        ports:
            - 10800:3000
        env_file: services/service-identity/.env
        environment:
            - RMQ_HOST=rabbitmq
            - RMQ_USER=username
            - RMQ_PASS=password
            - EVENTSTORE_HOST=eventstore
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - local

    rabbitmq:
        container_name: rabbitmq
        healthcheck:
            test: ["CMD", "nc", "-z", "localhost", "5672"]
            interval: 30s
            timeout: 10s
            retries: 5
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - local
        volumes:
            - type: volume
              source: rabbitmq-volume-data
              target: /var/lib/rabbitmq
            - type: volume
              source: rabbitmq-volume-logs
              target: /var/log/rabbitmq

    eventstore:
        container_name: eventstore
        image: ghcr.io/eventstore/eventstore:21.10.0-alpha-arm64v8
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        ports:
            - "1113:1113"
            - "2113:2113"
        networks:
            - local
        volumes:
            - type: volume
              source: eventstore-volume-data
              target: /var/lib/eventstore
            - type: volume
              source: eventstore-volume-logs
              target: /var/log/eventstore
