apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: hire.debens.app
    namespace: prod
    annotations:
        cert-manager.io/issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/rewrite-target: /employment/cv.pdf
spec:
    ingressClassName: nginx
    tls:
        - hosts:
              - hire.debens.app
          secretName: tls-prod-ingress-http
    rules:
        - host: hire.debens.app
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: minio
                            port:
                                name: s3
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: letsencrypt-prod
    namespace: prod
spec:
    acme:
        email: a.debens@gmail.com
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
            - http01:
                  ingress:
                      class: nginx
---

