---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tokens
  namespace: dev
spec:
  encryptedData:
    access_secret: AgC26wS7ZJ6ufULROZn2iJ8iNshJUuGl5NzGoEYXO6ujFAcmd2XKOxqqV0WPxbVC0u0oiOq20v+SHMEfLGhNAd1imEpEbprzWJK+R1pR22Z7YOcksBqX6ZUWdhrbQf3IAoXdJH1wOVJYyi9jqtadqywGfnDxgqEhWyeozN1+6VAVkhLsB1/uuBQoKBUeFU6HWkT/d+haFkNVFSmSUshg5pjLc/S9v8Z355SFLsJI6pYb16wXPzKvVjT3Cxvamar7+Lxfhx+85ANSiBoHQrnZTKyvq30eTDXuQW0d0bPoxCOVY+EHfQycflx1sj31cJoeR4mDPDTY0tSDe8kxuAqYpHptAbj3L9mfsfaahN2zV+9Yl13uq2naxxLtaZwcldax2l/RctBya2awUKpE5utYurADN7cSBRvBpD6UKlliyT+HIk3pJdwM8zRCxvFDct/uqrmG74Ml9pM6GNcpwm0pi2czs1rj5stmHLHsYVXDoat/jyD8vs/rTnrc6Ot4jReEvurXefVqWwGY5w25BYK11JuUkRlN5dQm+cOwlGRhrQ2x/IGmW8HYUZM0wqotxkucmu/mlIwK11uwEIUIvhnWPEh8yhgt4K1Hi8xwCkkwMbgMQ4RA78j424MJVmF0koouKXeKN8HKmtO+sSsLRU34D7cpE+pSJ4lvkBRQmF9UGwEyOB29EbASpLxza4JctSBR9F/BzA0AA4CMcAbsczAql8PkmiRA3dpUk3uJ270cRqXNaFvXnNc=
    refresh_secret: AgBR9cnyrCxNemGgIUeUg9b5AzhblM5lDXQSqtcdm8AP4Gdwr/jDwyp08IkveJdUNRQGYRG2/wh9n0W56ByUF9KipEU+A7yJ6vF6Njc+ELRzjwpeCt5VAqCAJTGlS8AgVkDiqI21bIjC+YDRfy2wnDw2Ktw1/Ew6R9+mv8hg7/iTeDPR5s72igQrGfxQIsjVormfwa68AEQNiZ2OwdJ7kHlqqCM/BmYrlJ46HMHmwIet9nqe1eCT3W82/6skImA/efr7oC08/WZFP9FpmutAvyTq1rpqjFfgnhaSQgOB9p/H+wK0WCj3XuXpZkTS880i3yv5Mxto0ubQd40INaIiaOSAZ/dhZKJfjzdt896ly8nUNr50XqcH8go4+aYzoXn7VAkLRpuJcEw/CNmj569rq7YbkT6R9h2TSUQGphVvaRUVeD+iiha7uVymBBB0nbHDUIK/ipQlLixqZwuNcY6L0nrl/tPArYRce5h0flRKWk6JMoLy/yz9/4PfQGYiXBc3ckK8+UmXpGxsTW6xgvufKkm60iz4Q2rl3loxbb28Li3x3nI8mhCcisraqrXUqjIuu5l8TWYAQVY4m13kitT9+p3aUheSETxptEkfygFT66yzvYApHLvf+lVwkneXjMXjsp08/O9yl45pBO4+9rJIA3MkCswFQ2CGmSjRvLvdq1Le785VYMkczcz94u44uYa2WJCjvaiR1/JITSSGQ6uK20H6ep7m6f9yNfnhn2X0vlIVWwBufew=
  template:
    metadata:
      creationTimestamp: null
      name: tokens
      namespace: dev
