version: '3'

networks:
    local:
        driver: bridge

volumes:
    eventstore-volume-data:
    eventstore-volume-logs:

services:
    rabbitmq:
        container_name: rabbitmq
        healthcheck:
            test: ['CMD', 'nc', '-z', 'localhost', '5672']
            interval: 30s
            timeout: 10s
            retries: 5
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - local
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
            - ./conf/rabbitmq:/etc/rabbitmq

    identity.eventstore:
        container_name: identity.eventstore
        image: ghcr.io/eventstore/eventstore:21.10.0-alpha-arm64v8
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        ports:
            - '1113:1113'
            - '2113:2113'
        networks:
            - local
        volumes:
            - type: volume
              source: eventstore-volume-data
              target: /var/lib/eventstore
            - type: volume
              source: eventstore-volume-logs
              target: /var/log/eventstore

    hanko:
        image: debens/hanko:latest
        command: serve --config /etc/config/config.yaml all
        restart: unless-stopped
        depends_on:
            hanko-db-migrate:
                condition: service_completed_successfully
        ports:
            - '8000:8000' # public
            - '8001:8001' # admin
        volumes:
            - type: bind
              source: ./conf/hanko/config.yml
              target: /etc/config/config.yaml
        networks:
            - local
        environment:
            - PASSWORD_ENABLED

    hanko-db:
        image: postgres:12-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=hanko
            - POSTGRES_PASSWORD=hanko
            - POSTGRES_DB=hanko
        healthcheck:
            test: pg_isready -U hanko -d hanko
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 30s
        networks:
            - local

    hanko-db-migrate:
        image: debens/hanko:latest
        command: --config /etc/config/config.yaml migrate up
        restart: on-failure
        depends_on:
            hanko-db:
                condition: service_healthy
        networks:
            - local
        volumes:
            - type: bind
              source: ./conf/hanko/config.yml
              target: /etc/config/config.yaml

    mailslurper:
        image: marcopas/docker-mailslurper:latest
        ports:
            - '8080:8080' # web UI
            - '8085:8085'
        networks:
            - local
